import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

//import COmponent
import Navbar from "./components/Navbar";
import Search from "./components/Search";
import DisplayPokemon from "./components/DisplayPokemon";

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Search Pokemon App",
  description: "Generated by create next app",
};



export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        <Search />
        {children}
      </body>
    </html>
  );
}
